### ISSUE TITLE
Sticky posts are difficult to see.

### ISSUE THREAD

**Issue by brotatos** [CalPolyIEEE/ieee#289]
For quite some time, sticky posts have been taken out of the 'recent posts' portion of the front page and shifted to the left of the page. I feel that this takes sticky posts out of focus when visiting the website (and allows users to easily miss otherwise important notifications).

In the future, I'd like to place sticky posts above the 'recent posts' section of the landing page. This will bring the users' attention immediately to what the admins of the site have deemed most significant.

**Comment by jhladky** [comment]
Not an issue anymore. :nail_care:
